[evolution]
population_size = 250
crossover_point_count = 1
crossover_rate = 0.7
mutation_rate = 0.3
generations = 100
elitism_percentage = 0.01
selection_size = 7
selection_type = "tournament"
seed = 0

[fitness]
test_case_count = 100
target_function = "(x^3)*y+y^3"


[bitstring_individual]
enabled = false
genome_size = 200

[tree_individual]
enabled = false
max_depth = 8
initial_depth = 2
operand_set = ["+", "-", "*", "/", ">", "<", "=", "%"]
variable_set = ["armies","generals","cities","mountains","neutral_cells","owned_cells","opponent_cells","fog_cells","structures_in_fog","owned_land_count","owned_army_count","opponent_land_count","opponent_army_count","timestep","priority"]
terminal_set = ["1.0"]

[grammar_tree]
enabled = false
genome_size = 20

[action_tree]
enabled = true
opponent_type = "random"
max_steps = 500
actions = ["Pass", "Cell_i", "Cell_j", "Direction", "Split"]
max_action_size = 5
weights_count = 20
weights_column_count = 12
server_addr = "127.0.0.1:8080"
train_weights_first = false
fitness_selection_percentage = 0.25
switch_training_target_step =10

[metrics]
csv_enabled = true
csv_file = "default_metrics.csv"
