[evolution]
population_size = 50
crossover_point_count = 1
crossover_rate = 0.7
mutation_rate = 0.3
generations = 10
elitism_percentage = 0.2
selection_size = 10
selection_type = "tournament"
seed = 0

[fitness]
test_case_count = 3
target_function = "(x^3)*y+y^3"


[bitstring_individual]
enabled = false
genome_size = 200

[tree_individual]
enabled = false
max_depth = 12
initial_depth = 5
operand_set = ["+", "-", "*", "/"]
variable_set = [
  "army_diff",

  "land_diff",

  "visible_cities_count",
  "visible_mountains_count",
  "army_ratio",
  "land_ratio",
  "border_pressure",
  "timestep",
]
terminal_set = []

[grammar_tree]
enabled = false
genome_size = 20

[action_tree]
enabled = true
opponent_type = "random"
max_steps = 1000
weights_count = 50
weights_column_count = 3
server_addr = "127.0.0.1:5000"
train_weights_first = false
fitness_selection_percentage = 0.1
switch_training_target_step = 10
connection_pool_size = 100
connection_timeout = "30s"
health_check_timeout = "30s"


[[action_tree.actions]]
name = "pass"
value = 2

[[action_tree.actions]]
name = "cell_i"
value = 10

[[action_tree.actions]]
name = "cell_j"
value = 10


[[action_tree.actions]]
name = "direction"
value = 4

[[action_tree.actions]]
name = "split"
value = 2

[metrics]
csv_enabled = true
csv_file = "default_metrics.csv"
