[evolution]
population_size = 10
crossover_point_count = 1
crossover_rate = 0.7
mutation_rate = 0.3
generations = 10
elitism_percentage = 0.01
selection_size = 7
selection_type = "tournament"
seed = 0

[fitness]
test_case_count = 100
target_function = "(x^3)*y+y^3"


[bitstring_individual]
enabled = false
genome_size = 200

[tree_individual]
enabled = false
max_depth = 12
initial_depth = 5
operand_set = ["+", "-", "*", "/"]
variable_set = [
  "my_total_army",
  "opp_total_army",
  "army_diff",

  "my_land_count",
  "opp_land_count",
  "land_diff",

  "neutral_count",
  "fog_count",
  "visible_cities_count",
  "visible_mountains_count",

  "army_ratio",
  "land_ratio",

  "border_pressure",

  "timestep",

  "distance_to_enemy_general",
  "distance_to_nearest_city",
]
terminal_set = ["1.0"]

[grammar_tree]
enabled = false
genome_size = 20

[action_tree]
enabled = true
opponent_type = "random"
max_steps = 500
actions = ["Pass", "Cell_i", "Cell_j", "Direction", "Split"]
max_action_size = 5
weights_count = 5
weights_column_count = 4
server_addr = "127.0.0.1:5000"
train_weights_first = false
fitness_selection_percentage = 0.25
switch_training_target_step = 10
connection_pool_size = 20
connection_timeout = "30s"
health_check_timeout = "30s"

[metrics]
csv_enabled = true
csv_file = "default_metrics.csv"
