[evolution]
population_size = 500
crossover_point_count = 1
crossover_rate = 0.7
mutation_rate = 0.05
generations = 50
elitism_percentage = 0.1
seed = 42

[fitness]
test_case_count=20
target_function = "x * y + 3 * 2"


[bitstring_individual]
enabled = false
genome_size = 200

[tree_individual]
enabled = true
max_depth = 7
initial_depth = 3
primitive_set = ["+", "-", "*", "/"]
terminal_set = ["x", "y", "1.0", "2.0", "3.0"]

[metrics]
csv_enabled = true
csv_file = "default_metrics.csv"
