[evolution]
population_size = 500
crossover_point_count = 1
crossover_rate = 0.7
mutation_rate = 0.3
generations = 400
elitism_percentage = 0.01
selection_size = 7
selection_type = "tournament"
seed = 42

[fitness]
test_case_count=100
target_function = "(x^3)*y+y^3"


[bitstring_individual]
enabled = false
genome_size = 200

[tree_individual]
enabled = true
max_depth = 8
initial_depth = 2
operand_set = ["+", "-", "*", "/"]
variable_set = ["x", "y"]
terminal_set = ["1.0", "2.0", "3.0"]

[grammar_tree]
enabled = false
genome_size = 20

[metrics]
csv_enabled = true
csv_file = "default_metrics.csv"
