[evolution]
population_size = 20
crossover_point_count = 2
crossover_rate = 0.7
mutation_rate = 0.3
generations = 100
elitism_percentage = 0.01
selection_size = 3
selection_type = "tournament"
seed = 42

[fitness]
test_case_count = 3
target_function = "(x^3)*y+y^3"


[bitstring_individual]
enabled = false
genome_size = 200

[tree_individual]
enabled = false
max_depth = 10
initial_depth = 5
operand_set = ["+", "-", "*", "/", "^",]
variable_set = [
  "army_diff",
  "land_diff",
  "distance_to_enemy_general",
  "enemy_general_x",
  "max_owned_army_x",
  "max_owned_army_y",
  "enemy_general_y",
  "min_city_x",
  "min_city_y",
  "visible_cities_count",
  "visible_mountains_count",
  "army_ratio",
  "land_ratio",
  "border_pressure",
]
terminal_set = []

[grammar_tree]
enabled = false
genome_size = 20

[action_tree]
enabled = true
opponent_type = "expander"
max_steps = 600
weights_count = 15
weights_column_count = 7
server_addr = "127.0.0.1:5000"
train_weights_first = false
fitness_selection_percentage = 0.1
switch_training_target_step = 5
connection_pool_size = 100
connection_timeout = "30s"
health_check_timeout = "30s"


[[action_tree.actions]]
name = "pass"
value = 2

[[action_tree.actions]]
name = "cell_i"
value = 8

[[action_tree.actions]]
name = "cell_j"
value = 8


[[action_tree.actions]]
name = "direction"
value = 4

[[action_tree.actions]]
name = "split"
value = 2

[metrics]
csv_enabled = true
csv_file = "test_small_argmax.csv"

[logging]
level = "info"
