[evolution]
population_size = 2000
crossover_point_count = 2
mutation_rate = 0.05
mutation_points = [10, 50]
generations = 200
elitism_percentage = 0.1
seed = 123

[bitstring_individual]
enabled = true
genome_size = 512

[tree_individual]
enabled = false
max_depth = 1
min_depth = 0
primitive_set = ["+", "-", "*", "/"]
terminal_set = ["x", "y", "1.0", "2.0"]
