[evolution]
population_size = 500
crossover_point_count = 1
crossover_rate = 0.9
mutation_rate = 0.05
generations = 50
elitism_percentage = 0.1
selection_size = 7
selection_type = "tournament"
seed = 42


[fitness]
target_function=""
test_case_count=20

[bitstring_individual]
enabled = true
genome_size = 200

[tree_individual]
enabled = false
max_depth = 1
min_depth = 0
operand_set = ["+", "-", "*", "/"]
variable_set = ["x"]
terminal_set = ["1.0", "2.0"]

[grammar_tree]
enabled = false
genome_size = 20


[metrics]
csv_enabled = true
csv_file = "medium_metrics.csv"
